### ISSUE TITLE
Inconsistent indentation in redfishMockupServer.py

### ISSUE THREAD

**Issue by MoshiBin** [DMTF/Redfish-Mockup-Server#107]
redfishMockupServer.py has inconsistent indentation. Sometimes indents are 4 spaces, while other times they're 8 spaces.

Example:

```python
def dict_merge(dct, merge_dct):
        """
        https://gist.github.com/angstwad/bf22d1822c38a92ec0a9 modified
```

Next function immediately after that:

```python
def clean_path(path, isShort):
    """clean_path
```

**Comment by glimchb** [comment]
@mraineri can you please run
```
pip install black
black redfishMockupServer.py
```
and propose PR? I could do it myself, but don't want to override proper `git blame` on the entire code ?
