### ISSUE TITLE
docker tag `latest` is misleading, it is 1y old

### ISSUE THREAD

**Issue by glimchb** [DMTF/Redfish-Mockup-Server#122]
see https://hub.docker.com/r/dmtf/redfish-mockup-server/tags?page=&page_size=&ordering=&name=latest

```
Last pushed a year ago by [dmtf](https://hub.docker.com/u/dmtf)
```

I think it is best to remove this tag completely or as alternative keep it up2date with every release

@MoshiBin @mraineri fyi

**Comment by mraineri** [comment]
I thought this step in our workflow should be updating it whenever we hit the release button...

https://github.com/DMTF/Redfish-Mockup-Server/blob/main/.github/workflows/release.yml#L86C1-L93C43

**Comment by mraineri** [comment]
Nevermind, that'll push to a specific tag; this might be an issue with how we have DockerHub set up. It might be pointing to "master" instead of "main" for setting up the "latest" tag...

**Comment by mraineri** [comment]
Yeah, that's the issue... unfortunately I'm getting an error when I go into the DockerHub build settings for the project, but I'm able to go into other projects and update their automated builds to point to "main".

**Comment by MoshiBin** [comment]
The workflow in `release.yml` only tags a specific release - if we want to keep `:latest` updated we should setup another workflow that triggers on push to `main`. Created #124 to add a `:latest` build on pushes to `main`.

**Comment by mraineri** [comment]
> The workflow in `release.yml` only tags a specific release - if we want to keep `:latest` updated we should setup another workflow that triggers on push to `main`. Created #124 to add a `:latest` build on pushes to `main`.

I'd like to get the configuration fixed on DockerHub; I have all other projects set up there to automatically trigger a build when there is activity on "main", but there's an issue specifically with the Redfish-Mockup-Server project on DockerHub where it prevents me from even adjusting the configurations.

**Comment by glimchb** [comment]
@MoshiBin check alternative just to push latest on release #125
@mraineri if you can fix DockerHub config, that's also fine

**Comment by mraineri** [comment]
I currently have a support ticket out on DockerHub to get the page fixed; hopefully that'll be done soon and we don't have to make any changes to workflows.

**Comment by MoshiBin** [comment]
I guess it depends on whether we want latest to point to the latest code in git, or the latest release. I’ve seen both cases in action.

Regarding triggering the builds from Docker hub, I think doing so reduces the transparency of how these images get built. Case in point, this build did not succeed for a while but there was no indication in the repo that something went wrong. As an added bonus, pushing in a GitHub Actions workflow also allows us to publish the image to GitHub’s own registry, not just Docker Hub.

**Comment by mraineri** [comment]
That's a good point; I'm convinced
