### ISSUE TITLE
procedure required

### ISSUE THREAD

**Issue by sundeep95** [DMTF/Redfish-Mockup-Server#16]
Hello
I am new to this.
I am using redfish-profile-simulator (https://github.com/DMTF/Redfish-Profile-Simulator) and got the output on localhost on ubuntu.
Can I implement this python file on top it?
If yes, Can you please provide the procedure steps.

Thanks

**Comment by mraineri** [comment]
@sundeep95 Did you mean to file an issue against the Profile Simulator? What this tool does is take an existing set of JSON files and creates a local webserver to act as a Redfish service; this tool doesn't run on top of the Profile Simulator.

**Comment by sundeepkumargorantla** [comment]
Thank you..
 I understood that this tool cannot be implemented on top of profile simulator.
But how this tool can be exactly implemented on existing JSON files.
Can you please provide the detailed procedure or any example to understand the extent of functionality of the code like whether its checks compatibility of payload before performing PATCH operation

**Comment by sundeep95** [comment]
Thank you..
I understood that this tool cannot be implemented on top of profile simulator.
But how this tool can be exactly implemented on existing JSON files.
Can you please provide the detailed procedure or any example to understand the extent of functionality of the code like whether its checks compatibility of payload before performing PATCH operation

**Comment by mraineri** [comment]
In the Redfish Mockup Server, there is no support for the PATCH operation; all PATCH requests are rejected, so there's no payload validation done by the Mockup Server for PATCH operations.

**Comment by mraineri** [comment]
1/11: Closing; PATCH is not supported on the Mockup Server
