### ISSUE TITLE
Incorrect Behavior after doing a sequence of Post Delete Post operations on a collection

### ISSUE THREAD

**Issue by phucdang18** [DMTF/Redfish-Mockup-Server#33]
The collection is originally: 
![image](https://user-images.githubusercontent.com/22107141/42168782-90ec08ae-7dd7-11e8-9ed0-a11488ef12bd.png)
After doing a sequence of 
Post {'a':1}
Delete  /redfish/v1/Chassis/Blade1
Post {'b':2}
The collection becomes
![image](https://user-images.githubusercontent.com/22107141/42168931-eca4b34e-7dd7-11e8-82c9-263fb6b3c349.png)

The server ends up with 2 new members with the same URI. This happens dues to the way the redfishMockupServer names new member `newpath = '/{}/{}'.format(xpath, len(members) + 1)`

In addition, The redfishMockupServer updates 'Members@odata.count' after a Post operation, but doesn't update 'Members@odata.count' after a delete operation

**Comment by tomasg2012** [comment]
Should be fixed in branch `post-del-fix`.

**Comment by tomasg2012** [comment]
Closed with latest PR.
