### ISSUE TITLE
Add SubmitTestMetricReport Action

### ISSUE THREAD

**Issue by JonHass** [DMTF/Redfish-Mockup-Server#45]
Need support for Telemetry model SubmitTestMetricReport Action.  The MetricReport JSON document generated from Action parameters should be sent to any Subscriber and the generated report should be persisted in the TelemetryService.MetricReports collection (in memory only).  Only the last version of a specific MetricReport (based on the MetricReport Name) should be persisted.

**Comment by mraineri** [comment]
Fixed in PR #47
