### ISSUE TITLE
option --port  does not work for Redfish Mockup Server, version 1.0.7

### ISSUE THREAD

**Issue by El-H-git** [DMTF/Redfish-Mockup-Server#51]
option -P does not work for Redfish Mockup Server, version 1.0.7 . It gives the following error:

sh-4.2# python redfishMockupServer.py -H 172.17.0.8 -P 8003
redfishMockupServer.py
Redfish Mockup Server, version 1.0.7
program: redfishMockupServer.py
Hostname: 172.17.0.8
Port: 8000
dir path specified by user:None
response time: 0 seconds
Serving Mockup in abs real directory path:/RGB-telemetry/Redfish-Mockup-Server
Traceback (most recent call last):
  File "redfishMockupServer.py", line 755, in <module>
    main(sys.argv)
  File "redfishMockupServer.py", line 732, in main
    fpath = myServer.construct_path('/redfish/v1', 'index.json')
AttributeError: 'HTTPServer' object has no attribute 'construct_path'
sh-4.2# python redfishMockupServer.py -H 127.0.0.1 -P 8000
redfishMockupServer.py
Redfish Mockup Server, version 1.0.7
program: redfishMockupServer.py
Hostname: 127.0.0.1
Port: 8000
dir path specified by user:None
response time: 0 seconds
Serving Mockup in abs real directory path:/RGB-telemetry/Redfish-Mockup-Server
Traceback (most recent call last):
  File "redfishMockupServer.py", line 755, in <module>
    main(sys.argv)
  File "redfishMockupServer.py", line 732, in main
    fpath = myServer.construct_path('/redfish/v1', 'index.json')
AttributeError: 'HTTPServer' object has no attribute 'construct_path'

sh-4.2# python redfishMockupServer.py -H 172.17.0.8
redfishMockupServer.py
Redfish Mockup Server, version 1.0.7
program: redfishMockupServer.py
Hostname: 172.17.0.8
Port: 8000
dir path specified by user:None
response time: 0 seconds
Serving Mockup in abs real directory path:/RGB-telemetry/Redfish-Mockup-Server
Serving Redfish mockup on port: 8000
running Server...

**Comment by billdodd** [comment]
Use lower-case `-p` (or `--port`) for the port option. Upper-case `-P` (or `--ssdp`) is for the SSDP listener option.

It does look like the usage help statement needs to be cleaned up some.

**Comment by billdodd** [comment]
Actually, yes, I see that `--port` does not seem to be working. But lower-case `-p` still works. Not sure why `--port` isn't working...

**Comment by El-H-git** [comment]
Thanks
