### ISSUE TITLE
Enhance fidelity of POST to Collection

### ISSUE THREAD

**Issue by billdodd** [DMTF/Redfish-Mockup-Server#58]
The existing Mockup-Server support for POSTing to an existing Collection is very helpful. But the fidelity could be improved with some relatively simple enhancements:

1. Add `Id`, `Name`, `@odata.id`, and `@odata.type` properties to the newly created resource
2. Return the new resource in the response body along with an HTTP 201 Created (instead of HTTP 204 No Content)

**Comment by mraineri** [comment]
Closing; addressed by recent PR
