### ISSUE TITLE
Blade System Mockup Server

### ISSUE THREAD

**Issue by maroskukan** [DMTF/Redfish-Mockup-Server#82]
Hello, first of all thanks for all the hard work done on Redfish. I really enjoy working with local mockup server that provides the sample rack mounted server experience.

Would it be possible to provided mock files in this repo for other systems you have available on your website? I am testing some python scripts and it would be great to test against a Blade system. Unfortunately I do not have one available to create a mockup from it.

Thanks.

**Comment by mraineri** [comment]
There are mockups you can download from the DMTF site here: https://www.dmtf.org/dsp/DSP2043

You can use the `-D` argument on the unzipped directory to specify whatever mockup you'd like.

We really only envisioned embedded one mockup for ease of use of first timers so they don't need to specify the `-D` argument.

**Comment by maroskukan** [comment]
@mraineri thank you for the link I will give it a try.
