### ISSUE TITLE
CORS support

### ISSUE THREAD

**Issue by donzef** [DMTF/Redfish-Mockup-Server#86]
Question:

I noticed that CORS (Cross-origin Resource Sharing) support has been removed silently in version 1.0.9. This feature allows JavaScript GUI simulators calling the Redfish-Mokcup-Server and providing a full BMC simulator (GUI + Redfish service).

Any chance to have it back ? 

Thanks.

**Comment by mraineri** [comment]
Do you know what version this was last working? I wasn't aware we ever had CORS support previously, and going through the pull requests merged up through 1.0.9 nothing sticks out to me as to when something like this was removed.

**Comment by donzef** [comment]
CORS support was in version 1.0.8. It is not there in version 1.0.9.

![image](https://user-images.githubusercontent.com/42031605/143401554-559983c9-f018-42b7-8943-2c1bede87d57.png)

**Comment by mraineri** [comment]
I've been looking through the assets attached to the releases (https://github.com/DMTF/Redfish-Mockup-Server/releases) and I can't find the same references you're seeing for version 1.0.8 and 1.0.7. Could those have been added by someone after downloading the source from GitHub?

**Comment by donzef** [comment]
<<<Could those have been added by someone after downloading the source from GitHub?>>>
This is the only possibility !

I'll investigate on my side where I got this code from.... Closing for now.

Sorry.
