### ISSUE TITLE
enhancement: Content-Length header as an option on command line ?

### ISSUE THREAD

**Issue by donzef** [DMTF/Redfish-Mockup-Server#87]
Versions 1.1.6 and 1.1.7 introduce the Content-Length header in responses. This breaks scripts piping responses in JSON processors like [jq](https://stedolan.github.io/jq/).

Would it be possible to have the Content-Length included in responses only if asked on the command line ?

Thanks

**Comment by mraineri** [comment]
We can consider adding that option, but it concerns me that additional HTTP headers in the response would break tools like that. It's pretty common for services to have additional headers outside the Redfish spec definition, and Content-Length is a pretty common response header that's included. The JSON part of the response is solely in the response body, so I'm not sure why they'd be using the HTTP response headers in the JSON processing. Are you able to provide examples of the issue you're seeing?

**Comment by donzef** [comment]
It appears that when I added the CORS support in version 1.1.7, I broke something in related to headers.

I am definitively not a programmer !

Closing for now, waiting for the issue #86 to be closed.
