### ISSUE TITLE
SSL with self-signed certificate issue

### ISSUE THREAD

**Issue by shesamian** [DMTF/Redfish-Mockup-Server#96]
I am trying to use a self-signed certificate with Docker and I am wondering if it's even supported with Redfish-Mockup-Server

```
openssl req -new -x509 -keyout cert.pem -out cert.pem -days 365 -nodes
```

And run Docker:
```
docker run --rm --name asb88rn24u01  -p 80:80/tcp -p 443:443/tcp -v C:\asb88rn24u01:/mockup -v C:\cert.pem:/temp/cert.pem -v C:\key.pem:/temp/key.pem dmtf/redfish-mockup-server:latest -D /mockup  --cert /temp/cert.pem --key /temp/key.pem -p 443
```

It successfully connects but its having trouble with the certificate version being served
![image](https://github.com/DMTF/Redfish-Mockup-Server/assets/107954668/eed75b8a-2132-471b-ba1b-5dc367b0450f)

logs:
![image](https://github.com/DMTF/Redfish-Mockup-Server/assets/107954668/f4a02def-633b-4bca-98a7-04a6dc437463)

**Comment by noxxi** [comment]
Looks like a failure to use the `-s|--ssl` option of the server in order to actually do HTTPS and not plain HTTP
